### ISSUE TITLE
Permission to fork and modify 

### ISSUE THREAD

**Issue by YonVclaw** [jetelain/cTab#21]
My group has been running a modified version of Riouken CTAB for some time, I had a list of changes I wanted to do but never had the time, and then I found your version on steam, 

Any change or addition made in our forks you would be welcome to incorporate back into the main branch.

Our major changes currently are.
- CAS Menu and icons
- All items are inventory items and not locked to the device slot
- Lots of additional icons  in general
- On the to do list i we have new models for the android and tablet, ( just not had the time to convert them to p3d)

**Comment by jetelain** [comment]
Sorry, I forgot to reply you earlier : it's open-source ! Feel free to fork, modify, and incorporate back. Any help is welcome !

It's under GNU GPLv2 (cTab part) and MIT (cTab IRL part) licences.

**Comment by YonVclaw** [comment]
Thank you, I always ask when dealing with ARMA, you would be surprised to how many folks do not understand what open source means.
