### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/cTab#32]
Getting into a vehicle that is driven by AI procudes this in the rpt file:
```
23:14:24 Error in expression <river _vehicle || { {_deviceLevel == 2} || {_player == _vehicle call cTab_fnc_ge>
23:14:24   Error position: <|| {_player == _vehicle call cTab_fnc_ge>
23:14:24   Error ||: Type code, expected Bool
23:14:24 File z\ctab_irl\addons\connect\functions\fnc_updateDevices.sqf..., line 21
```

**Comment by jetelain** [comment]
Hi, thanks for the report, it have been fixed 
https://github.com/jetelain/cTab/commit/54cbab9d497d4b19facb3aed248cdaf9d1dc6724

New version have been published on Workshop with the fix.
