### ISSUE TITLE
How to compile/test this repo (ctab c# webapp)?

### ISSUE THREAD

**Issue by DE-Schmitt** [jetelain/cTab#36]
I want to modify and play around with a clone of your repo. More precisely: The ctab webapp. Thus I installed Visual Studio Code including github and C# extension and also installed .net 7. I have some trouble compilating this repo because a simple click on run/debug leads to errors like \cTabIRL\cTabWebApp\Hub\CTabHub.cs(7,7): error CS0246: Type- or namespace name "Arma3TacMapLibrary" not found. I also see stuff like \Arma3TacMap\Arma3TacMapLibrary\Arma3TacMapLibrary.csproj was skipped because it was not found. Is there some documentation on how to compile your repo? Is there another repo "Arma3TacMap" I have to download in order to compile cTab webapp?

**Comment by jetelain** [comment]
Hi, in fact it depends on an additional repo : https://github.com/jetelain/Arma3TacMap
I should add a submodule to avoid problems

**Comment by jetelain** [comment]
I've added a submodule, should be easier to build

**Comment by DE-Schmitt** [comment]
Ok, thanks for adding the submodule. That brings me one step further in the direction of successfully compiling the webapp some time in the future :-D

When I simply hit "Run and Debug" in Visual Studio Code, a launch file for QrFontBuilder is auto created (even though I did not explicitly required QrFontBuilder) and this runs fine. It generates some PAAs. BUT I want to run and compile the webapp (!), not the font builder. I want a browser window to open and show the webapp locally. But I cannot manage to do this. I now auto created the following launch.json

{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "msedge",
            "request": "launch",
            "name": "Microsoft Edge mit \"Localhost\" starten",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

This open Edge browser which shows the following error message:

"400 Bad Request
HttpException('Invalid HTTP request form (expected: authority or absolute, got: relative)',)"

Any idea?

**Comment by jetelain** [comment]
Hi,
I'm using Visual Studio 2022, I'm not familiar with dotnet development with Visual Studio Code.

To build and run from command line (requires dotnet sdk 7) :
- Single player mode : `dotnet run --project cTabWebApp\cTabWebApp.csproj`
- Web hosted mode : `dotnet run --project cTabWebApp\cTabWebApp.csproj -c DebugCloud`
Then open your browser on http://localhost:5000/
