### ISSUE TITLE
Real time export not exporting metis markers

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/cTab#44]
Error is in the metis marker functions but  I suspect they error out because they're getting the wrong arguments.

1. Create basic mission on Fapovo
2. Host as local multiplayer directly in the editor
3. Open up cTab IRL in browser and select "Load tactical map". I'm selecting this PLANOPS map https://maps.plan-ops.fr/ViewMap/5039?t=anvQLU07RyU_USh4PMdXg-95QozGC0gjvxllvmRArXQ
4. Error pop up
![image](https://user-images.githubusercontent.com/57712666/224031186-b72dc668-2e72-468a-8afe-2f5ef6b32386.png)
5. Lines are created correctly, all metis markers are missing.
![image](https://user-images.githubusercontent.com/57712666/224031401-bd145523-8c4d-49b2-97aa-4be836c34819.png)

Attached rpt (changing file ending to upload)
[Arma3_x64_2023-03-09_13-19-55.txt](https://github.com/jetelain/cTab/files/10931842/Arma3_x64_2023-03-09_13-19-55.txt)

Using the latest version of cTab, SIT and Metis Markers
The one time export in the editor does include Metis Markers.

**Comment by MildlyInterested** [comment]
Probably solved by https://github.com/jetelain/cTab/pull/39

**Comment by jetelain** [comment]
Yes, it have been solved by #39.

**Comment by jetelain** [comment]
New version have been pushed on the workshop, should be OK now.
