### ISSUE TITLE
Map view sometimes crashes game

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/cTab#49]
Sometimes while opening the map view in multiplayer the whole game will crash.
Have created a ticket on the Arma 3 Feedback tracker with crash dumps in the hopes that a dev can give some insight.
https://feedback.bistudio.com/T172503

**Comment by jetelain** [comment]
Hi, It might be related to the extension required for cTab to connect. Do you have any rpt file when the issue occurs ?

**Comment by MildlyInterested** [comment]
Ah sure thing, just realized I completely forgot to upload them.. 
[arma3_x64_2023-05-14_19-43-23.zip](https://github.com/jetelain/cTab/files/11524139/arma3_x64_2023-05-14_19-43-23.zip)
dump files can be found in the FT ticket.

**Comment by jetelain** [comment]
Fixed on Arma side

**Comment by jetelain** [comment]
Latest reports from users show that Arma fix is not enough
