### ISSUE TITLE
#define DISABLE_COMPILE_CACHE set by accident?

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/cTab#50]
Looking at this commit (https://github.com/jetelain/cTab/commit/e99dd0bdfe80a91dbb22bd931fd96b2b6f9de0b5) to remember the commands for different marker channel  I noticed you uncommented `DISABLE_COMPILE_CACHE` in https://github.com/jetelain/cTab/blob/e99dd0bdfe80a91dbb22bd931fd96b2b6f9de0b5/cTabIRL/%40cTabIRL/addons/tacmap/script_component.hpp#L5 
Guessing thats debugging/dev related that's not supposed to be active in the master branch?

**Comment by jetelain** [comment]
Hi, Yes this not intentional. I will fix this in next update
