### ISSUE TITLE
Height should be used as dialog base dimension

### ISSUE THREAD

**Issue by Input-BDF** [jetelain/cTab#62]
As Ultrawide screens get more common and 1080p is at least the most common base, cTabs device UI-Dialogs should use screen height as base dimension. With 32:9, 16:10, 16:9 and 4:3 this will cover all this resolutions much better and constant. Using width gives to much tolerance and produces overflows.

A simple switch can achieve this. e.g.: FBCB2 [Line 1-2 cTab_FBCB2_dialog.hpp](https://github.com/jetelain/cTab/blob/d5f992ff824b449050e19619b4d8d9dcfa3fb207/%40cTab/addons/cTab/FBCB2/cTab_FBCB2_dialog.hpp#L1):

```
#define GUI_GRID_W	(safezoneW)
#define GUI_GRID_H	(GUI_GRID_W * 4/3)
```
should become
```
#define GUI_GRID_H	(safezoneH)
#define GUI_GRID_W	(GUI_GRID_H * 3/4)
```
Setting Markers seem to work after the switch. The drawback of this the vertical alignment of marker menu does not fit anymore, but havn't figured out, where it is set. Maybe you can give me a clue and I'll try to create a PR.

Howerver there still has to be some resize tweaking done. Please see screenshots attached of my first tests:
![cTAB_Dimension_Issue_comparison](https://github.com/user-attachments/assets/1a3ae808-c891-415c-ba9f-f332e37a2cdd)

**Comment by jetelain** [comment]
Hi, do you use the "Extended" or "Non extended" mode ?

**Comment by Input-BDF** [comment]
I'm currently a litte bit lost. Could you please give me a short clue what your understanding of "Extended" and "non Extended" mode is?

The screenshots above where taken with cTab devices "opened" so that map markers etc. can be placed. In this mode device sizes cause issues on wide/ultrawide screens. Sizes of "minimized" devices and their positions are good so far.

cTab is configured "as is" in addon options.

**Comment by Input-BDF** [comment]
Just looked into. In my case they are not called "extended", but thinks you mean the settings under "Aspect Ratio". At least this affects the UI-layout as you say. 

Aspect Ratio: Auto (Ultrawide Stretch)
The rest..
Display Mode: Fullscreen
Resolution: 3840x1080 (32:9)
Interface Size: Small

Using the Auto (Ultrawide Non-Stretch), Auto (Non Stretch 32:9)/(Stretch 32:9) (the last why ever) for Aspect Ration seem to limit safezoneW under/around 1920px horizontal in the middle of the "screen"-layout. In this case cTab-device sizes fit, but this settings have (lots of) other sideeffects. 
A friend of mine has as 1440p Ultrawide. Maybe I can catch him up the days to support tests on different resolutions.

**Comment by jetelain** [comment]
Hi, I've adjusted values to have a good result on 16:9, 32:9 (Ultra Wide), 32:9 (Triple Head)

| | 16:9 | Triple Head | Ultra Wide  |
|-----------------|---|---------------------|---------------------|
| Android | ![android_full](https://github.com/user-attachments/assets/bd25d1e1-5ee9-4c12-8ea4-03d6849f0b07)    | ![android_full](https://github.com/user-attachments/assets/b3a9203a-ca1d-4972-afcd-18a20a7d88ce)    | ![android_full](https://github.com/user-attachments/assets/43e12073-22b1-4b7f-9b7d-5ba433fb2a04)    |
| Android | ![android_overlay](https://github.com/user-attachments/assets/107461f5-30fd-402e-b6a5-587f26d39596) | ![android_overlay](https://github.com/user-attachments/assets/213214a4-198e-4104-a589-5b573321410d) | ![android_overlay](https://github.com/user-attachments/assets/58da1a25-67e8-4649-970e-993f032a0afa) |
| DAGR    | ![dagr_full](https://github.com/user-attachments/assets/62a29be7-877f-410e-89ce-5edeef19875a)       | ![dagr_full](https://github.com/user-attachments/assets/48101e50-5877-410d-9441-257d3b0d7f6d)       | ![dagr_full](https://github.com/user-attachments/assets/0263adc6-a57d-4c30-bb73-41a9b02946f9)       |
| DAGR    | ![dagr_overlay](https://github.com/user-attachments/assets/60380045-65cb-4922-be1f-2e0eb2e86423)    | ![dagr_overlay](https://github.com/user-attachments/assets/0ae8b244-6d36-4723-a476-5e31c09aff89)    | ![dagr_overlay](https://github.com/user-attachments/assets/787eb66d-9909-4c9e-803c-bf24ce043b53)    |
| FBCB2   | ![fbcb2](https://github.com/user-attachments/assets/48683ca3-ebf8-4178-8c5b-54f317c85c4b)           | ![fbcb2](https://github.com/user-attachments/assets/b679721e-64f0-4672-a117-936a336c10a7)           | ![fbcb2](https://github.com/user-attachments/assets/7aa63bc8-49cd-428e-8c07-7ff22c4129b3)           |
| Tablet  | ![tablet](https://github.com/user-attachments/assets/f7268f14-0771-4e86-9033-c6031ffc9f4c)          | ![tablet](https://github.com/user-attachments/assets/0266d962-8e02-4977-bcfa-adf8829d7a12)          | ![tablet](https://github.com/user-attachments/assets/fbafd146-d1ce-40bb-b616-7accc114ed56)          |
| TAD     | ![tad_full](https://github.com/user-attachments/assets/9e8d5832-5187-4921-8a58-7808a339d0ad)        | ![tad_full](https://github.com/user-attachments/assets/bd24e425-9924-4200-8053-9adcf48a2ce5)        | ![tad_full](https://github.com/user-attachments/assets/89e1bd34-686d-4e5e-ae80-febf291c2913)        |
| TAD     | ![tad_overlay](https://github.com/user-attachments/assets/a0758f6d-2064-4729-895a-c748e513261f)     | ![tad_overlay](https://github.com/user-attachments/assets/536e1b5e-d49b-43ed-865a-eda3bcf3a64c)     | ![tad_oberlay](https://github.com/user-attachments/assets/90e960db-5b21-4a60-9385-67c5a7f35341)     |
