### ISSUE TITLE
How to build with HEMTT

### ISSUE THREAD

**Issue by mrschick** [jetelain/cTab#67]
I'm attempting to build [@cTab](https://github.com/jetelain/cTab/tree/master/%40cTab) with HEMTT [v1.13.4](https://github.com/BrettMayson/HEMTT/releases/tag/v1.13.4), but it throws several errors, first of all that `.hemtt/project.toml` is missing. However, even when renaming the existing `base.toml` to `project.toml` there are several compilation errors thrown, here's some of them:
```
   ┌─ addons/compass/HorizontalCompass.hpp:16:15
   │
16 │     y = 0.845 * safezoneH + safezoneY;
   │               ^ found "*" but expected one of "U", "_", "j", "7", "J", "v", "r", "O", "k", "G", "5", "L", "p", "t", "Z", "S", "T", "q", "0", "y", "E", "D", "}", "4", "P", "l", "C", ";", "M", "n", "w", "B", "g", "Y", "8", "b", "u", "m", "s", "K", "3", "N", "V", "d", "6", "I", "F", "H", "o", "h", "z", "W", "f", "i", "e", "Q", "x", "c", "1", "9", "A", "X", "a", "R", "2"
   │
   = note: The processed output of the line with the error was:
           y = 0.845 * safezoneH + safezoneY;


error[CE1]: property's value could not be parsed.
  ┌─ addons/core/CfgVehicles.hpp:6:31
  │
6 │                 displayName = $STR_ctab_core_aceMenu;
  │                               ^^^^^^^^^^^^^^^^^^^^^^ invalid value
  │
  = help: use quotes `"` around the value
```

Is there an alternative way to building it that I'm missing?

**Comment by jetelain** [comment]
Hi,
I've not updated the code to be compatible with recent versions of HEMTT. It requires a lot of changes. I'm still using an old version of HEMTT on my side.

**Comment by jetelain** [comment]
I'm using `HEMTT 0.7.6`

**Comment by mrschick** [comment]
Thanks 🤙🏻

I'll write a PR in the afternoon to add that info to the documentation.
